# Generated by Django 4.2.18 on 2025-03-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="متن پیام"),
                ),
                (
                    "created",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="تاریخ ایجاد پیام شمسی",
                    ),
                ),
                (
                    "updated",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, null=True, verbose_name="تاریخ تغییر پیام شمسی"
                    ),
                ),
                (
                    "is_ok",
                    models.BooleanField(default=False, verbose_name="تایید شده / نشده"),
                ),
                (
                    "CommentProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.product",
                        verbose_name="محصول پیام",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="Product.customercomment",
                        verbose_name="زیر دسته",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر پیام",
                    ),
                ),
            ],
            options={
                "verbose_name": " نظرات کاربران ",
                "verbose_name_plural": "نظرات در مورد کالا کاربران",
            },
        ),
        migrations.CreateModel(
            name="LikesCustomerComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.BooleanField(default=False)),
                (
                    "CustomerComment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.customercomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پسندیدن نظرات",
                "verbose_name_plural": "پسندیدن نظرات",
                "unique_together": {("user", "CustomerComment")},
            },
        ),
    ]
