# Generated by Django 4.2.18 on 2025-03-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_customercomment_likescustomercomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likescustomercomment",
            name="CustomerComment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isLiked",
                to="Product.customercomment",
            ),
        ),
    ]
