# Generated by Django 4.2.18 on 2025-03-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_alter_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
    ]
