# Generated by Django 4.2.18 on 2025-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moshfegh_products_category", "0001_initial"),
        ("Product", "0005_remove_product_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="childe",
                to="moshfegh_products_category.productcategory",
                verbose_name="دسته بندی ها",
            ),
        ),
    ]
