# Generated by Django 4.2.18 on 2025-05-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_account", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
