# Generated by Django 4.2.18 on 2025-05-24 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("new_account", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codeVarifySms",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="کد تایید پیامکی",
                    ),
                ),
                (
                    "codeVarifySmsDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تایید پیامکی"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
