# Generated by Django 4.2.18 on 2025-05-24 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("new_account", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserData",
            new_name="UserCode",
        ),
    ]
