# Generated by Django 4.2.18 on 2025-07-06 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("new_account", "0004_rename_userdata_usercode"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choiceField",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name=" عنوان اجتماعی ",
                    ),
                ),
                (
                    "SAL",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="سال تولد "
                    ),
                ),
                (
                    "MAH",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name=" ماه تولد "
                    ),
                ),
                (
                    "ROZ",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name=" روز تولد "
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": " اطلاعات شخصی کاربران ",
                "verbose_name_plural": " اطلاعات شخصی ",
            },
        ),
    ]
