# Generated by Django 4.2.18 on 2025-04-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moshfeghi_order", "0003_alter_orderdetail_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childrens",
                to="moshfeghi_order.order",
                verbose_name="سبد خرید",
            ),
        ),
    ]
