# Generated by Django 4.2.18 on 2025-03-14 18:37

from django.db import migrations, models
import moshfeghi_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان سایت")),
                ("address", models.CharField(max_length=400, verbose_name="آدرس")),
                ("phone", models.CharField(max_length=50, verbose_name="تلفن")),
                ("mobile", models.CharField(max_length=50, verbose_name="تلفن همراه")),
                ("fax", models.CharField(max_length=50, verbose_name="فکس")),
                ("email", models.EmailField(max_length=50, verbose_name="ایمیل")),
                (
                    "about_us",
                    models.TextField(blank=True, null=True, verbose_name="درباره ی ما"),
                ),
                (
                    "copy_right",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="متن کپی رایت",
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=moshfeghi_setting.models.upload_image_path,
                        verbose_name="تصویر لوگو",
                    ),
                ),
                (
                    "TermsAndRules_field",
                    models.TextField(blank=True, null=True, verbose_name=" شرایط "),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "مدیریت تنظیمات",
            },
        ),
    ]
