# Generated by Django 4.2.18 on 2025-03-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moshfeghi_slider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="price",
            field=models.IntegerField(default=1000, verbose_name="قیمت"),
            preserve_default=False,
        ),
    ]
