# Generated by Django 4.2.18 on 2025-03-13 17:54

from django.db import migrations, models
import moshfeghi_slider.models


class Migration(migrations.Migration):

    dependencies = [
        ("moshfeghi_slider", "0002_slider_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderDown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=100, null=True, verbose_name="ادرس"
                    ),
                ),
                (
                    "description1",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "imageSlider",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=moshfeghi_slider.models.upload_image_path,
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلایدر پایین",
                "verbose_name_plural": "اسلایدرها پایین",
            },
        ),
    ]
